# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a4d922bb16347e10301b993283228e5"
name = "pwa-proxy"
application_url = "https://shopify-pwa-proxy.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy"

[auth]
redirect_urls = [ "https://shopify-pwa-proxy.vercel.app/api/auth" ]

[app_proxy]
url = "/pwa"
subpath = "pwa"
prefix = "apps"
